### PR TITLE
Consolidate pagination metadata nil pointer checks

### LINKED ISSUE #408: [BUG] - Listing region availabilities causes a panic
**Describe the bug**
Listing region availability panics when using the default text output. Available plans are listed, but finishes with an error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1466972]

goroutine 1 [running]:
github.com/vultr/vultr-cli/v3/cmd/regions.(*RegionsAvailabilityPrinter).Paging(0xc000212950?)
	github.com/vultr/vultr-cli/v3/cmd/regions/printer.go:110 +0x12
github.com/vultr/vultr-cli/v3/cmd/printer.(*Output).Display(0xc0000976b0, {0x1649540, 0xc000212950}, {0x0?, 0x0?})
	github.com/vultr/vultr-cli/v3/cmd/printer/printer.go:80 +0x162
github.com/vultr/vultr-cli/v3/cmd/regions.NewCmdRegion.func4(0xc0001e0100?, {0xc000212150?, 0x4?, 0x156a19c?})
	github.com/vultr/vultr-cli/v3/cmd/regions/regions.go:110 +0xc7
github.com/spf13/cobra.(*Command).execute(0xc0001de900, {0xc000212120, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x194f660)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/vultr/vultr-cli/v3/cmd.Execute()
	github.com/vultr/vultr-cli/v3/cmd/root.go:62 +0x1a
main.main()
	github.com/vultr/vultr-cli/v3/main.go:7 +0xf
```

**To Reproduce**
1. `vultr-cli regions availability ams`
2. Availabilities are listed, but a panic occurs.

**Expected behavior**
No panic.

**Screenshots**

**Desktop (please complete the following information where applicable:**
 - OS: darwin
 - Version: vultr-cli 3.0.0

**Additional context**

The issue seems to be called by a nil `Meta` field on [this line](https://github.com/vultr/vultr-cli/blob/master/cmd/regions/printer.go#L110C1-L111C1). Happy to open a PR to patch this if the project is open to external contributions.

### PR DESCRIPTION
**Pull request by PaulSonOfLars**
## Description
Consolidate pagination metadata nil pointer checks, fixing a panic in the region availability lists (#408)

## Related Issues
Fixes #408 

### Checklist:

* [Y] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [Y] Have you linted your code locally prior to submission?
* [Y] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by optik-aper** [comment]
@PaulSonOfLars I like what you're doing here.  Thanks for submitting the PR.  I'm gonna look at this more closely and think it through.  It's probably going to need a rebase once my PR goes in, so if you want to hold off to push the lint fixes until then, that'd be swell.

**Comment by PaulSonOfLars** [comment]
@optik-aper no problem! 
Sure thing, let me know when your PR is in and I'll rework this one

**Comment by optik-aper** [comment]
Just merged it!

**Review by optik-aper — APPROVED** [review]
This seems a little redundant but I think this is a good safety mechanism to check for `nil` structs.  I'm merging it and might tweak it in the future.  Thanks for the PR

**Pull request merged**
